import {Dimensions, StyleSheet} from 'react-native';

let deviceW = Dimensions.get('window').width;
let deviceH = Dimensions.get('window').height;

export const styles = StyleSheet.create({
  containerContent: {
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    margin: 5,
    borderRadius: 20,
  },
  containerTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: 15,
    marginRight: 15,
    alignItems: 'center',
    borderBottomWidth: 1,
  },
  containerTitleText: {
    color: 'white',
    fontSize: 20,
    fontWeight: 'bold',
  },
  inlineContainer: {
    flex: 1,
    flexDirection: 'row',
    margin: 20,
    padding: 15,
    backgroundColor: '#22334430',
    borderRadius: 20,
  },
  containerContentElements: {
    alignItems: 'center',
    flex: 1,

    justifyContent: 'space-between',
    height: 150,
  },
  firstPlaceElement: {
    // flex: 10,
    margin: 5,
    width: 80,
    height: 80,
    backgroundColor: '#22334430',
    borderRadius: 50,
    borderColor: 'gold',
    borderWidth: 1.5,
  },
  secondPlaceElement: {
    // flex: 9,
    margin: 5,
    width: 75,
    height: 75,
    backgroundColor: '#22334430',
    borderRadius: 50,
    borderColor: 'silver',
    borderWidth: 1.5,
  },
  thirdPlaceElement: {
    // flex: 8,
    margin: 5,
    width: 70,
    height: 70,
    backgroundColor: '#22334430',
    borderRadius: 50,
    borderColor: 'brown',
    borderWidth: 1.5,
  },
  notTopElement: {
    margin: 5,
    width: 65,
    height: 65,
    backgroundColor: '#22334430',
    borderRadius: 50,
    borderColor: 'grey',
    borderWidth: 1,
  },
  inlineContainerElements: {
    // flex: 1,

    width: 80,
    height: 80,
    margin: 5,
    borderColor: '#65CC7B',
    // borderBottomWidth: 5,
    // borderStartWidth: 5,
    // borderEndWidth: 5,
    // borderTopWidth: 5,
    borderWidth: 1.5,
    backgroundColor: '#0057B6',
    borderRadius: 40,
  },
  inlineContainerRoundElements: {
    // flex: 1,
    // flex: 1,
    resizeMode: 'cover',
    margin: 5,
    width: 90,
    height: 90,
    borderRadius: 90,
    backgroundColor: '#22334430',
  },
  toolbarAbsolutePosition: {
    // position: 'absolute',
    // top: 0,
    // bottom: 0,
    // left: 0,
    // right: 0,
    zIndex: 10,
  },
  contentListAbsolutePosition: {
    position: 'absolute',
    top: 50,
    bottom: 0,
    left: 0,
    right: 0,
    // zIndex: 10,
  },
});
